name: {{ cookiecutter.env_name }}
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - flake8
  - jupyter
  - jupytext
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - python=3
  - pip:
    - -e .
